### ISSUE TITLE
Update package.json to contain repository field

### ISSUE THREAD

**Issue by emilhem** [mirhampt/node-recaptcha#12]
The package.json file for node-recaptcha is missing the repository field even though it obviously have a respository. Could this be done by @mirhampt ?

This would fix the warning that comes up everytime you do something with the npm in a directory where node-recaptcha is installed.

**Comment by felipou** [comment]
+1

**Comment by emilhem** [comment]
Fixed in my pull request #15

**Comment by mirhampt** [comment]
Merged and released as v1.2.1 on npm. Thanks!
